pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo 'This is a build stage'
            }
        }
        stage('Test') {
            steps {
                echo 'This is a test stage'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
         stage('Complete') {
            steps {
                echo 'Job Complete'
            }
        }
    }
}
