pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo 'This is a build stage'
            }
        }
        stage('Test') {
            steps {
                echo 'This is a test stage'
            }
        }
        stage('Deliver') {
            steps {
                echo 'Delivery stage'
            }
        }
         stage('Complete') {
            steps {
                echo 'Job Complete'
            }
        }
    }
}
